packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

minimumReleaseAge: 4320

catalogMode: strict
cleanupUnusedCatalogs: true
catalog:
  "@biomejs/biome": 2.5.9
  "@changesets/cli": ^2.31.1
  "@digdir/designsystemet": ^1.20.0
  "@digdir/designsystemet-css": ^1.20.0
  "@digdir/designsystemet-react": ^1.20.0
  "@digdir/designsystemet-types": ^1.20.0
  "@digdir/designsystemet-web": ^1.20.0
  "@mdx-js/react": ^3.1.1
  "@navikt/aksel-icons": ^8.16.1
  '@storybook/addon-a11y': ^10.5.10
  "@storybook/addon-docs": ^10.5.10
  "@storybook/addon-themes": ^10.5.10
  '@storybook/addon-vitest': ^10.5.10
  "@storybook/react-vite": ^10.5.10
  '@tanstack/react-form': ^1.33.5
  "@tsdown/css": ^0.22.14
  '@types/node': ^24.13.3
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.4
  "@u-elements/u-progress": ^1.0.1
  '@vitest/browser-playwright': ^4.1.11
  '@vitest/coverage-v8': ^4.1.11
  clsx: ^2.1.1
  playwright: ^1.62.1
  react: ^19.2.8
  react-docgen-typescript: ^2.4.0
  react-dom: ^19.2.8
  react-dropzone: ^20.1.1
  storybook: ^10.5.10
  tsdown: ^0.22.14
  typedoc: ^0.28.20
  typedoc-plugin-markdown: ^4.12.0
  typescript: ^6.0.3
  vite: ^8.2.2
  vitest: ^4.1.11
  vitest-browser-react: ^2.2.0
  zod: ^4.4.3
