import {
  EXPERIMENTAL_Suggestion,
  EXPERIMENTAL_SuggestionClear,
  EXPERIMENTAL_SuggestionEmpty,
  EXPERIMENTAL_SuggestionInput,
  EXPERIMENTAL_SuggestionList,
  EXPERIMENTAL_SuggestionOption,
  EXPERIMENTAL_SuggestionToggle,
  type SuggestionClearProps,
  type SuggestionEmptyProps,
  type SuggestionInputProps,
  type SuggestionItem,
  type SuggestionListProps,
  type SuggestionMultipleProps,
  type SuggestionOptionProps,
  type SuggestionProps,
  type SuggestionSingleProps,
  type SuggestionToggleProps,
} from "@digdir/designsystemet-react";

export type {
  SuggestionClearProps,
  SuggestionEmptyProps,
  SuggestionInputProps,
  SuggestionItem,
  SuggestionListProps,
  SuggestionMultipleProps,
  SuggestionOptionProps,
  SuggestionProps,
  SuggestionSingleProps,
  SuggestionToggleProps,
};
export {
  EXPERIMENTAL_Suggestion,
  EXPERIMENTAL_SuggestionClear,
  EXPERIMENTAL_SuggestionEmpty,
  EXPERIMENTAL_SuggestionInput,
  EXPERIMENTAL_SuggestionList,
  EXPERIMENTAL_SuggestionOption,
  EXPERIMENTAL_SuggestionToggle,
};
